version: '3'

services:
  php:
    image: php:7.3-fpm
    volumes:
      - ./:/app
    working_dir: /app
  web:
    image: nginx:latest
    volumes:
      - ./:/app
    working_dir: /app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
